In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets, utils
import numpy as np
from random import shuffle
import tensorflow as tf
from sklearn.preprocessing import label_binarize

In [9]:
iris = datasets.load_iris()

X = iris.data[:100, :]
Y = iris.target[:100]
X_test = iris.data[100:, :]

logclf = LogisticRegression()
logclf.fit(X, Y)
print(X_test)

[[ 6.3  3.3  6.   2.5]
 [ 5.8  2.7  5.1  1.9]
 [ 7.1  3.   5.9  2.1]
 [ 6.3  2.9  5.6  1.8]
 [ 6.5  3.   5.8  2.2]
 [ 7.6  3.   6.6  2.1]
 [ 4.9  2.5  4.5  1.7]
 [ 7.3  2.9  6.3  1.8]
 [ 6.7  2.5  5.8  1.8]
 [ 7.2  3.6  6.1  2.5]
 [ 6.5  3.2  5.1  2. ]
 [ 6.4  2.7  5.3  1.9]
 [ 6.8  3.   5.5  2.1]
 [ 5.7  2.5  5.   2. ]
 [ 5.8  2.8  5.1  2.4]
 [ 6.4  3.2  5.3  2.3]
 [ 6.5  3.   5.5  1.8]
 [ 7.7  3.8  6.7  2.2]
 [ 7.7  2.6  6.9  2.3]
 [ 6.   2.2  5.   1.5]
 [ 6.9  3.2  5.7  2.3]
 [ 5.6  2.8  4.9  2. ]
 [ 7.7  2.8  6.7  2. ]
 [ 6.3  2.7  4.9  1.8]
 [ 6.7  3.3  5.7  2.1]
 [ 7.2  3.2  6.   1.8]
 [ 6.2  2.8  4.8  1.8]
 [ 6.1  3.   4.9  1.8]
 [ 6.4  2.8  5.6  2.1]
 [ 7.2  3.   5.8  1.6]
 [ 7.4  2.8  6.1  1.9]
 [ 7.9  3.8  6.4  2. ]
 [ 6.4  2.8  5.6  2.2]
 [ 6.3  2.8  5.1  1.5]
 [ 6.1  2.6  5.6  1.4]
 [ 7.7  3.   6.1  2.3]
 [ 6.3  3.4  5.6  2.4]
 [ 6.4  3.1  5.5  1.8]
 [ 6.   3.   4.8  1.8]
 [ 6.9  3.1  5.4  2.1]
 [ 6.7  3.1  5.6  2.4]
 [ 6.9  3.1  5.1  2.3]
 [ 5.8  2.7  5.1  1.9]
 [ 6.8  3.2

In [10]:
logclf.predict([[3.4, 1., 3.4, 5.3]])

array([1])

In [11]:
raw_data_set = datasets.load_iris() 
iris = np.column_stack([raw_data_set['data'], raw_data_set['target']]) 
iris = utils.shuffle(iris) 
target_multiclass = label_binarize(iris[:, -1], classes=[0, 1, 2])
print(iris[:3])
print(target_multiclass[:3]) # to take a look

[[ 6.3  2.9  5.6  1.8  2. ]
 [ 6.7  3.   5.   1.7  1. ]
 [ 5.2  3.4  1.4  0.2  0. ]]
[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [14]:
# Parameters
learning_rate = 0.001
training_epochs = 20
batch_size = 10
display_step = 1

# Network Parameters
n_hidden_1 = 25 # 1st layer number of neurons
n_hidden_2 = 25 # 2nd layer number of neurons
n_input = 4
n_classes = 3 # Iris total classes

# tf Graph input
X = tf.placeholder("float", [None, n_input])
Y = tf.placeholder("float", [None, n_classes])

# Store layers weight & bias
weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}


# Create model
def multilayer_perceptron(x):
    # Hidden fully connected layer with 256 neurons
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])
    # Hidden fully connected layer with 256 neurons
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    # Output fully connected layer with a neuron for each class
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    return out_layer

# Construct model
logits = multilayer_perceptron(X)

# Define loss and optimizer
loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
train_op = optimizer.minimize(loss_op)
# Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0.
        # Loop over all batches
        total_batch = int(150/batch_size)
        for i in range(total_batch):
            batch_x, batch_y = iris[i:i+batch_size,:4], target_multiclass[i:i+batch_size]
            # Run optimization op (backprop) and cost op (to get loss value)
            _, c = sess.run([train_op, loss_op], feed_dict={X: batch_x,
                                                            Y: batch_y})
            # Compute average loss
            avg_cost += c / total_batch
        # Display logs per epoch step
        if epoch % display_step == 0:
            print("Epoch:", '%04d' % (epoch+1), "cost={:.9f}".format(avg_cost))
    print("Optimization Finished!")

    # Test model
    pred = tf.nn.softmax(logits)  # Apply softmax to logits
    correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(Y, 1))
    # Calculate accuracy
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print("Accuracy:", accuracy.eval({X: iris[:,:-1], Y: target_multiclass}))

Epoch: 0001 cost=72.659586589
Epoch: 0002 cost=39.538881048
Epoch: 0003 cost=8.476602451
Epoch: 0004 cost=1.957590803
Epoch: 0005 cost=0.499719057
Epoch: 0006 cost=0.224368965
Epoch: 0007 cost=0.168023264
Epoch: 0008 cost=0.200913771
Epoch: 0009 cost=0.194624336
Epoch: 0010 cost=0.175710059
Epoch: 0011 cost=0.159462504
Epoch: 0012 cost=0.146668811
Epoch: 0013 cost=0.137588451
Epoch: 0014 cost=0.132418157
Epoch: 0015 cost=0.131610615
Epoch: 0016 cost=0.136162053
Epoch: 0017 cost=0.146575612
Epoch: 0018 cost=0.159174564
Epoch: 0019 cost=0.165223858
Epoch: 0020 cost=0.157894202
Optimization Finished!
Accuracy: 0.953333
